# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket         = "terraform-codium-state-terragrunt"
    dynamodb_table = "terraform-locking-terragrunt"
    encrypt        = true
    key            = "./terraform.tfstate"
    region         = "eu-west-1"
  }
}
